spring:
  application:
    name: bbp-config-service
  profiles:
    active: native
  cloud:
    #TODO add ability to fetch config from git repository
    config.server.native.searchLocations: classpath:/config/shared
server:
  port: 8000
eureka:
  client:
    registryFetchIntervalInSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/