spring:
  application:
    name: 'bbp-warehouse-service'
  mvc:
    favicon:
      enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: 'jdbc:postgresql://localhost:5450/warehouse'
    username: 'warehouseuser'
    password: 'docker'

    driver-class-name: 'org.postgresql.Driver'
server:
  port: 8050
eureka:
  client:
    registryFetchIntervalInSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
